name: check google-java-format

on:
  push:
    branches:
      - '1.0'
  pull_request:
    branches:
      - '1.0'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Set up Java
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: "temurin"
          java-version: 17
      - uses: axel-op/googlejavaformat-action@c1134ebd196c4cbffb077f9476585b0be8b6afcd # v4.0.0
        with:
          args: "--set-exit-if-changed"
